version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  order:
    build: ./order
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 9005:9005
    networks:
      - my-network

  warehouse:
    build: ./warehouse
    depends_on:
      rabbitmq:
        condition: service_healthy
      order:
        condition: "service_started"
    ports:
      - 9006:9006
    networks:
      - my-network

networks:
  my-network:
